# Day 4: Session 4C - The Derived-Column Pattern

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/4c_transforming_data.html)

Date: 09/03/2026

In [3]:
import pandas as pd
import numpy as np

url = 'https://eds-217-essential-python.github.io/data/marine_microplastics.csv'
plastics = pd.read_csv(url)

plastics.shape

(16245, 22)

In [2]:
m3 = plastics[plastics['Unit'] == 'pieces/m3'].copy()
m3.shape

(10178, 22)

In [9]:
m3.head()

,OBJECTID,Oceans,Regions,SubRegions,Sampling Method,Measurement,Unit,Density Range,Density Class,Short Reference,...,Organization,Keywords,Accession Number,Accession Link,Latitude,Longitude,Date,GlobalID,x,y
0,10008,Atlantic Ocean,NaN,NaN,Grab sample,0.020000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,-58.428300,-64.1640,2/3/2017 12:00:00 AM,1e5b8e71-037b-4887-a276-f1e4552acb1f,-64.1640,-58.428300
1,8680,Atlantic Ocean,NaN,NaN,Grab sample,0.008000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,-51.308200,-60.5467,11/17/2013 12:00:00 AM,a40f7f7c-1025-4aac-ad16-ee4cba196870,-60.5467,-51.308200
2,13257,Pacific Ocean,NaN,NaN,Manta net,0.019886,pieces/m3,0.005-1,Medium,Faure et al.2015,...,"Oceaneye Association, Switzerland",Oceaneye Association; Citizen Science,276422,https://www.ncei.noaa.gov/access/metadata/land...,-51.826667,-72.5750,12/26/2015 12:00:00 AM,febf79b8-7e2c-46e6-bc15-e08492ec2029,-72.5750,-51.826667
3,9676,Atlantic Ocean,NaN,NaN,Grab sample,0.018000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,-31.696000,-48.5600,8/11/2015 12:00:00 AM,a77121b2-e113-444e-82d9-7af11d62fdd2,-48.5600,-31.696000
4,6427,Pacific Ocean,NaN,NaN,Neuston net,0.000000,pieces/m3,0-0.0005,Very Low,Law et al.2014,...,Sea Education Association,SEA,211008,https://www.ncei.noaa.gov/access/metadata/land...,6.350000,-121.8500,12/18/2002 12:00:00 AM,be27c450-02ca-4261-8d89-cae21108e6cc,-121.8500,6.350000

In [ ]:
# double checking to see if the right filter was applied. we are only pulling out pieces/m3
plastics['Unit'].value_counts()

Unit
pieces/m3           10178
pieces/10 mins       5792
pieces kg-1 d.w.      275
Name: count, dtype: int64

In [ ]:
# naming new column pieces_per_liter from the calculation on Measurement column
m3['pieces_per_liter'] = m3['Measurement'] / 1000

In [12]:
m3[['Measurement', 'Unit', 'pieces_per_liter']].head(20)

    Measurement       Unit  pieces_per_liter
0      0.020000  pieces/m3          0.000020
1      0.008000  pieces/m3          0.000008
2      0.019886  pieces/m3          0.000020
3      0.018000  pieces/m3          0.000018
4      0.000000  pieces/m3          0.000000
5      0.013000  pieces/m3          0.000013
7      0.000000  pieces/m3          0.000000
8      0.006480  pieces/m3          0.000006
9      0.000000  pieces/m3          0.000000
10     0.138471  pieces/m3          0.000138
11     0.009968  pieces/m3          0.000010
12     0.000000  pieces/m3          0.000000
13     0.004425  pieces/m3          0.000004
14     0.004320  pieces/m3          0.000004
15     0.000000  pieces/m3          0.000000
16     0.003088  pieces/m3          0.000003
17     0.002160  pieces/m3          0.000002
18     0.012960  pieces/m3          0.000013
19     0.004800  pieces/m3          0.000005
24     0.019440  pieces/m3          0.000019

In [13]:
m3['pieces_per_liter'].describe()

count    10178.000000
mean         0.219409
std          2.599555
min          0.000000
25%          0.000000
50%          0.000007
75%          0.000050
max        110.480000
Name: pieces_per_liter, dtype: float64

In [ ]:
m3.shape
# added an extra column

(10178, 23)

In [15]:
m3['latitude_radians'] = m3['Latitude'] * 3.141592653589793 / 180

In [17]:
m3.shape
# checking to see if we added the extra column

(10178, 24)

### A column and a column

In [18]:
url = 'https://eds-217-essential-python.github.io/data/banana_index.csv'
foods = pd.read_csv(url, index_col='entity')
foods[['emissions_kg', 'land_use_kg', 'Bananas index (kg)']].head()

               emissions_kg  land_use_kg  Bananas index (kg)
entity
Ale                0.488690     0.811485            0.559558
Almond butter      0.387011     7.683045            0.443134
Almond milk        0.655888     1.370106            0.751002
Almonds            0.602368     8.230927            0.689721
Apple juice        0.458378     0.660629            0.524851

In [19]:
banana_emissions = foods.loc['Bananas', 'emissions_kg']
banana_emissions

0.87334957

In [20]:
foods['my_banana_index'] = foods['emissions_kg'] / banana_emissions
foods[['emissions_kg', 'Bananas index (kg)', 'my_banana_index']].head()

               emissions_kg  Bananas index (kg)  my_banana_index
entity
Ale                0.488690            0.559558         0.559558
Almond butter      0.387011            0.443134         0.443134
Almond milk        0.655888            0.751002         0.751002
Almonds            0.602368            0.689721         0.689721
Apple juice        0.458378            0.524851         0.524851

In [23]:
# this is telling us the crop or item that takes up the most land per emission
foods['land_per_emission'] = foods['land_use_kg'] / foods['emissions_kg']
foods['land_per_emission'].sort_values(ascending = False).head()

entity
Almond butter    19.852250
Almonds          13.664286
Beans            12.428466
Chickpeas        11.578514
Lentils          10.831714
Name: land_per_emission, dtype: float64

In [26]:
positive = m3[m3['Measurement'] > 0].copy()
positive.shape

(7091, 24)

In [30]:
positive['log10_measurement'] = np.log10(positive['Measurement'])
positive[['Measurement', 'log10_measurement']].head()

   Measurement  log10_measurement
0     0.020000          -1.698970
1     0.008000          -2.096910
2     0.019886          -1.701453
3     0.018000          -1.744727
5     0.013000          -1.886057

In [32]:
positive['log10_per_liter'] = np.log10(positive['pieces_per_liter'])

#### Tidying text with .str

In [ ]:
plastics[plastics['Keywords'] == 'R/V tara'].shape

# why did we get 0? be diligent and always check its not a spelling issue

(0, 22)

In [36]:
plastics['Keywords'].unique()[10:14]

array(['Amazon Continental Shelf', 'Antarctic Circumnavigation Expedition', 'R/V Tara ',
       'SV Mir; ORV Alguita; SV Sea Dragon; RV Stad Amsterdam'], dtype=object)

In [38]:
plastics[plastics['Keywords'] == 'R/V Tara '].shape

(23, 22)

In [ ]:
# lets get rid of the space
plastics['Keywords'] = plastics['Keywords'].str.strip()
plastics[plastics['Keywords'] == 'R/V Tara'].shape

(23, 22)

In [42]:
# this shows us what populates the column
plastics['Density Class'].value_counts()

Density Class
Medium       8029
Very Low     4155
Low          1944
High         1671
Very High     446
Name: count, dtype: int64

In [44]:
plastics['density_class'] = plastics['Density Class'].str.lower()
plastics['density_class'].value_counts()

density_class
medium       8029
very low     4155
low          1944
high         1671
very high     446
Name: count, dtype: int64

In [45]:
plastics['Oceans'].value_counts()

Oceans
Atlantic Ocean    14483
Pacific Ocean      1402
Arctic Ocean         69
Southern Ocean       20
Name: count, dtype: int64

In [47]:
plastics['ocean'] = plastics['Oceans'].str.replace(' Ocean' , '')
plastics['ocean'].value_counts()

ocean
Atlantic    14483
Pacific      1402
Arctic         69
Southern       20
Name: count, dtype: int64

In [48]:
url = 'https://eds-217-essential-python.github.io/data/marine_microplastics.csv'
plastics = pd.read_csv(url)

# Clean: drop the rows with no measurement (session 4A), then strip the stray
# whitespace out of Keywords (this session)
plastics = plastics.dropna(subset=['Measurement'])
plastics['Keywords'] = plastics['Keywords'].str.strip()

# Select one unit, so arithmetic means something (session 3B)
samples = plastics[plastics['Unit'] == 'pieces/m3'].copy()
samples = samples[samples['Measurement'] > 0].copy()

# Transform (this session)
samples['ocean'] = samples['Oceans'].str.replace(' Ocean', '')
samples['pieces_per_liter'] = samples['Measurement'] / 1000
samples['log10_measurement'] = np.log10(samples['Measurement'])

samples[['ocean', 'Measurement', 'pieces_per_liter', 'log10_measurement']].head()

      ocean  Measurement  pieces_per_liter  log10_measurement
0  Atlantic     0.020000          0.000020          -1.698970
1  Atlantic     0.008000          0.000008          -2.096910
2   Pacific     0.019886          0.000020          -1.701453
3  Atlantic     0.018000          0.000018          -1.744727
5   Pacific     0.013000          0.000013          -1.886057

In [49]:
samples.shape

(7091, 25)