# Session 7.0: Building a Table Row by Row
Date: 09/09/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/eurovision_contestants.csv'
eurovision = pd.read_csv(url)

contests = eurovision[eurovision['year'] != 2020].copy()
contests['decade'] = (contests['year'] / 10).astype(int) * 10

In [7]:
scores = pd.DataFrame({
    # dictionary of lists: each column is defined all at once
    "country": ["Norway", "Sweden", "Malta"], # col 1
    "entries": [58, 59, 32] # col 2
})

print(type(scores))

<class 'pandas.core.frame.DataFrame'>

In [5]:
pd.DataFrame(
    [ # list of dictionaries: each row is defined all at once
        {"country": "Norway", "entries": 58}, # row 1
        {"country": "Sweden", "entries": 59}, # row 2
        {"country": "Malta", "entries": 32} # row 3
     ]
)

  country  entries
0  Norway       58
1  Sweden       59
2   Malta       32

In [10]:
records = [] # step 1- start with an empty list

for decade, decade_data in contests.groupby('decade'):
    records.append({ # step 2- append one dictionary per group inside the loop
        'decade': decade,
        'entries': len(decade_data),
        'countries': decade_data['to_country'].nunique()
    })

pd.DataFrame(records) # step 3- turn the finished list into a dataframe

   decade  entries  countries
0    1950       43         12
1    1960      163         18
2    1970      176         22
3    1980      200         23
4    1990      236         34
5    2000      336         47
6    2010      408         46

In [ ]:
winners = []

for decade, decade_data in contests.groupby("decade"):
# find the average points_final by country in each decade:
    means = decade_data.groupby("to_country")["points_final"].mean()

# count the nu,ber of times a country was in the finals in each decade
    counts = decade_data.groupby("to_country")['points_final'].count()

# what is the index (country) associated with the max avg. points_final in each decade?
    best = means.idxmax()
    print(f"{decade} best country was {best}")

# append this decade to our winners 'list:
    winners.append(
        {
            "decade":decade, # current decade
            "country": best, # country that had the highest avg. points_final for this decade
            "finals": counts[best], # the number of times that country was in the finals
            "mean_points": means[best], # the average points_final for this country
        }
    )

decade_winners = pd.DataFrame(winners) # turn our list of dictionaries into a dataframe

decade_winners

1950 best country was France
1960 best country was United Kingdom
1970 best country was United Kingdom
1980 best country was Ireland
1990 best country was Ireland
2000 best country was Serbia
2010 best country was Bulgaria

   decade         country  finals  mean_points
0    1950          France       3    19.666667
1    1960  United Kingdom      10    23.100000
2    1970  United Kingdom      10    93.200000
3    1980         Ireland       9    99.222222
4    1990         Ireland      10   119.200000
5    2000          Serbia       2   214.000000
6    2010        Bulgaria       3   362.666667