# Day 3: Session 3B - The Filter Pattern

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/3b_filtering_data.html)

Date: 09/02/2026

In [42]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)
goleta.shape

(1962, 15)

In [43]:
goleta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1962 entries, 0 to 1961
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    1962 non-null   int64
 1   location_name  1962 non-null   object
 2   parameter      1962 non-null   object
 3   value          1962 non-null   float64
 4   unit           1962 non-null   object
 5   datetimeUtc    1962 non-null   object
 6   datetimeLocal  1962 non-null   object
 7   timezone       1962 non-null   object
 8   latitude       1962 non-null   float64
 9   longitude      1962 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     1962 non-null   object
 14  provider       1962 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 230.1+ KB

In [44]:
keep = goleta['value'] > 20 # can also assign this to a new object to save them

gt_20 = goleta[keep] # can also save this as a new object

gt_20.describe()

gt_20b = goleta[goleta['value'] > 20]

# Filter pattern is;
#
# df
#
# df_filtered = df[df['column'] > x]
# 
# can also wrap them 
#
# df_filtered = df[ (df['column'] > x) & (df['another column'] == y) ]

In [45]:
valid = (goleta['value'] > 20)
high_readings = goleta[valid]

high_readings.shape

(115, 15)

In [46]:
goleta[valid].describe()

       location_id       value      latitude     longitude  country_iso  isMobile  isMonitor
count        115.0  115.000000  1.150000e+02  1.150000e+02          0.0       0.0        0.0
mean        1186.0   25.373913  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
std            0.0    4.288829  7.136523e-15  2.854609e-14          NaN       NaN        NaN
min         1186.0   21.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
25%         1186.0   22.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
50%         1186.0   24.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
75%         1186.0   27.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
max         1186.0   40.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN

In [47]:
# Filter with text 

goleta['parameter'].value_counts()
ozone = goleta[ goleta['parameter'] == 'o3']
ozone.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [48]:
ozone.shape

(711, 15)

In [49]:
goleta[goleta['parameter'] == 'O3'].shape
# An empty result is not an error. Zero rows is a real answer, 
# and it usually means a spelling or capitalization problem rather than a fact about the data.

(0, 15)

In [50]:
print(goleta['parameter'].unique())
pm25 = goleta[goleta['parameter'] == 'pm25']

['o3' 'pm10' 'pm25']

In [51]:
# combining logical operators

valid = (goleta['parameter'] == 'pm25') & (goleta['value'] > 9)
goleta[valid].describe()

       location_id       value      latitude     longitude  country_iso  isMobile  isMonitor
count        128.0  128.000000  1.280000e+02  1.280000e+02          0.0       0.0        0.0
mean        1186.0   12.304688  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
std            0.0    2.678461  1.426669e-14  2.853339e-14          NaN       NaN        NaN
min         1186.0   10.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
25%         1186.0   10.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
50%         1186.0   11.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
75%         1186.0   14.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN
max         1186.0   22.000000  3.444530e+01 -1.198278e+02          NaN       NaN        NaN

In [52]:
# can also put it all together
goleta_filtered = goleta[
    (goleta['parameter'] == 'pm25') & (goleta['value'] > 9)]


goleta_filtered

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1261,1186,Goleta,pm25,14.0,µg/m³,2024-07-13T10:00:00+00:00,2024-07-13T03:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1265,1186,Goleta,pm25,10.0,µg/m³,2024-07-13T14:00:00+00:00,2024-07-13T07:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1270,1186,Goleta,pm25,10.0,µg/m³,2024-07-13T19:00:00+00:00,2024-07-13T12:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1313,1186,Goleta,pm25,12.0,µg/m³,2024-07-15T14:00:00+00:00,2024-07-15T07:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1314,1186,Goleta,pm25,11.0,µg/m³,2024-07-15T15:00:00+00:00,2024-07-15T08:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1953,1186,Goleta,pm25,16.0,µg/m³,2024-08-11T16:00:00+00:00,2024-08-11T09:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1954,1186,Goleta,pm25,16.0,µg/m³,2024-08-11T17:00:00+00:00,2024-08-11T10:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1955,1186,Goleta,pm25,13.0,µg/m³,2024-08-11T18:00:00+00:00,2024-08-11T11:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1956,1186,Goleta,pm25,14.0,µg/m³,2024-08-11T19:00:00+00:00,2024-08-11T12:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1957,1186,Goleta,pm25,10.0,µg/m³,2024-08-11T20:00:00+00:00,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [53]:
# negation in pandas world (not not, but is ~)

goleta[~(goleta['parameter'] == 'pm25')]

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1223,1186,Goleta,pm10,17.000,µg/m³,2024-08-11T20:00:00+00:00,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1224,1186,Goleta,pm10,23.000,µg/m³,2024-08-11T21:00:00+00:00,2024-08-11T14:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1225,1186,Goleta,pm10,18.000,µg/m³,2024-08-11T22:00:00+00:00,2024-08-11T15:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1226,1186,Goleta,pm10,27.000,µg/m³,2024-08-11T23:00:00+00:00,2024-08-11T16:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1227,1186,Goleta,pm10,23.000,µg/m³,2024-08-12T00:00:00+00:00,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [54]:
either_pollutant_high = goleta[
    ((goleta['parameter'] == 'pm25') & (goleta['value'] > 9))
    | ((goleta['parameter'] == 'pm10') & (goleta['value'] > 20))
]
either_pollutant_high.shape

(240, 15)

In [55]:
one_column = goleta['parameter']
one_column.isin

goleta['parameter'].isin(['03', 'pm10'])

0       False
1       False
2       False
3       False
4       False
        ...
1957    False
1958    False
1959    False
1960    False
1961    False
Name: parameter, Length: 1962, dtype: bool

In [56]:
goleta[~one_column.isnull()]
# keeping only the populated columns

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1957,1186,Goleta,pm25,10.000,µg/m³,2024-08-11T20:00:00+00:00,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1958,1186,Goleta,pm25,8.000,µg/m³,2024-08-11T21:00:00+00:00,2024-08-11T14:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1959,1186,Goleta,pm25,8.000,µg/m³,2024-08-11T22:00:00+00:00,2024-08-11T15:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1960,1186,Goleta,pm25,9.000,µg/m³,2024-08-11T23:00:00+00:00,2024-08-11T16:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1961,1186,Goleta,pm25,5.000,µg/m³,2024-08-12T00:00:00+00:00,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow