# Day 6: Session 6B - Long and Wide

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/6b_reshaping_data.html)

Date: 09/08/2026

In [1]:
import pandas as pd

base = 'https://eds-217-essential-python.github.io/data/'

goleta = pd.read_csv(base + 'openaq_goleta_measurments.csv')
santa_barbara = pd.read_csv(base + 'openaq_santa_barbara_measurments.csv')
cnsi = pd.read_csv(base + 'openaq_CNSI_measurments.csv')

print(goleta.shape)
print(santa_barbara.shape)
print(cnsi.shape)

(1962, 15)
(2266, 15)
(714, 15)

In [2]:
goleta.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [3]:
santa_barbara.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,27499,Santa Barbara,o3,0.022,ppm,2024-07-11T01:00:00+00:00,2024-07-10T18:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T02:00:00+00:00,2024-07-10T19:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T03:00:00+00:00,2024-07-10T20:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T04:00:00+00:00,2024-07-10T21:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,27499,Santa Barbara,o3,0.016,ppm,2024-07-11T05:00:00+00:00,2024-07-10T22:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [4]:
cnsi.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,2812592,CNSI Roof Top,pm25,4.4,µg/m³,2024-07-11T01:00:00+00:00,2024-07-10T18:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity
1,2812592,CNSI Roof Top,pm25,4.4,µg/m³,2024-07-11T02:00:00+00:00,2024-07-10T19:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity
2,2812592,CNSI Roof Top,pm25,4.6,µg/m³,2024-07-11T04:00:00+00:00,2024-07-10T21:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity
3,2812592,CNSI Roof Top,pm25,4.2,µg/m³,2024-07-11T05:00:00+00:00,2024-07-10T22:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity
4,2812592,CNSI Roof Top,pm25,4.5,µg/m³,2024-07-11T06:00:00+00:00,2024-07-10T23:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity

In [5]:
aq = pd.concat([goleta, santa_barbara, cnsi])

aq.shape

(4942, 15)

In [6]:
aq.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'datetimeLocal', 'timezone', 'latitude', 'longitude',
       'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='object')

In [11]:
aq.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [12]:
aq.isnull().sum()

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      4942
isMobile         4942
isMonitor        4942
owner_name          0
provider            0
dtype: int64

In [21]:
goleta['site'] = 'Goleta'
santa_barbara['site'] = 'Santa Barbara'
cnsi['site'] = 'CNSI'

aq = pd.concat([goleta, santa_barbara, cnsi], ignore_index = True)

aq.tail()



# pd.concat by defalt preserves the index values of each dataframe.
# This means the indicies can repeat, especially if the indicies are row numbers...
# ignore_index=True discards the old numbering and renumbers the result from 0 to 4,941

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider,site
4937,2812592,CNSI Roof Top,pm25,9.9,µg/m³,2024-08-11T20:00:00+00:00,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI
4938,2812592,CNSI Roof Top,pm25,9.1,µg/m³,2024-08-11T21:00:00+00:00,2024-08-11T14:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI
4939,2812592,CNSI Roof Top,pm25,8.7,µg/m³,2024-08-11T22:00:00+00:00,2024-08-11T15:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI
4940,2812592,CNSI Roof Top,pm25,8.0,µg/m³,2024-08-11T23:00:00+00:00,2024-08-11T16:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI
4941,2812592,CNSI Roof Top,pm25,7.9,µg/m³,2024-08-12T00:00:00+00:00,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI

In [ ]:
messy = pd.concat([goleta, santa_barbara, cnsi])

print(messy.index[:3]) # give me the first three values
print(messy.index[-3:]) # give me the last three values

Index([0, 1, 2], dtype='int64')
Index([711, 712, 713], dtype='int64')

In [26]:
aq_test = pd.concat([cnsi, goleta, santa_barbara], ignore_index = True)

aq_test.tail()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider,site
4937,27499,Santa Barbara,pm25,11.0,µg/m³,2024-08-11T20:00:00+00:00,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow,Santa Barbara
4938,27499,Santa Barbara,pm25,10.0,µg/m³,2024-08-11T21:00:00+00:00,2024-08-11T14:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow,Santa Barbara
4939,27499,Santa Barbara,pm25,7.0,µg/m³,2024-08-11T22:00:00+00:00,2024-08-11T15:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow,Santa Barbara
4940,27499,Santa Barbara,pm25,7.0,µg/m³,2024-08-11T23:00:00+00:00,2024-08-11T16:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow,Santa Barbara
4941,27499,Santa Barbara,pm25,9.0,µg/m³,2024-08-12T00:00:00+00:00,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow,Santa Barbara

In [27]:
aq_test.value_counts('site')

site
Santa Barbara    2266
Goleta           1962
CNSI              714
Name: count, dtype: int64

In [30]:
two_sites =  pd.concat([goleta, cnsi], ignore_index = True)

In [34]:
two_sites.shape

(2676, 16)

In [36]:
aq[['site', 'parameter', 'value', 'unit', 'datetimeLocal']].head()

     site parameter  value unit              datetimeLocal
0  Goleta        o3  0.025  ppm  2024-07-11T18:00:00-07:00
1  Goleta        o3  0.028  ppm  2024-07-11T19:00:00-07:00
2  Goleta        o3  0.029  ppm  2024-07-11T20:00:00-07:00
3  Goleta        o3  0.027  ppm  2024-07-11T21:00:00-07:00
4  Goleta        o3  0.026  ppm  2024-07-11T22:00:00-07:00

In [ ]:
# the index should be a categorical variable that will create new columns
# the columns are going to come from the one column and create new columns from the different ones
# the values will be coming from the value row
means = aq.pivot_table(index = 'site', columns = 'parameter', values = 'value')

means

parameter            o3       pm10      pm25
site
CNSI                NaN        NaN  6.083473
Goleta         0.022470  14.972921  6.480926
Santa Barbara  0.019822  17.563969  6.172324

# by default the pivot table takes the means of the values argument/column.

df.pivot_table(index='rows', columns='columns', values='numbers')
####            ↑             ↑                  ↑
####             what labels ->   what labels    ->    what goes
####             the rows   ->   the columns    ->    in the cells

In [40]:
aq.pivot_table(index = 'site', columns = 'parameter', values = 'value', aggfunc = 'count')

parameter         o3   pm10   pm25
site
CNSI             NaN    NaN  714.0
Goleta         711.0  517.0  734.0
Santa Barbara  734.0  766.0  766.0

#### use the aggfun argument to specify the aggregation function. 
#### same list of functions as we had in .agg()

In [41]:
means['pm25']

site
CNSI             6.083473
Goleta           6.480926
Santa Barbara    6.172324
Name: pm25, dtype: float64

In [42]:
means.loc['Goleta', 'pm25']

6.4809264305177114

In [45]:
print(aq.groupby(['site', 'parameter'])['value'].mean())

site           parameter
CNSI           pm25          6.083473
Goleta         o3            0.022470
               pm10         14.972921
               pm25          6.480926
Santa Barbara  o3            0.019822
               pm10         17.563969
               pm25          6.172324
Name: value, dtype: float64

In [46]:
flat = means.reset_index()

flat

parameter           site        o3       pm10      pm25
0                   CNSI       NaN        NaN  6.083473
1                 Goleta  0.022470  14.972921  6.480926
2          Santa Barbara  0.019822  17.563969  6.172324

In [48]:
aq.pivot_table(index = 'parameter', columns = 'site', values = 'value')

site           CNSI     Goleta  Santa Barbara
parameter
o3              NaN   0.022470       0.019822
pm10            NaN  14.972921      17.563969
pm25       6.083473   6.480926       6.172324

In [49]:
aq['site'].value_counts()

site
Santa Barbara    2266
Goleta           1962
CNSI              714
Name: count, dtype: int64

In [52]:
counts = aq['site'].value_counts().reset_index()

counts

            site  count
0  Santa Barbara   2266
1         Goleta   1962
2           CNSI    714

In [53]:
counts = counts.rename(columns = {'count' : 'n_readings'})

In [54]:
# Learn the two lines below as a single move, because you will use them constantly 

# counts = df['column'].value_counts().reset_index()

# counts = counts.rename(columns={'count': 'a_better_name'})

In [55]:
summary = pd.merge(flat, counts, on = 'site')

In [56]:
aq['hour'] = aq['datetimeLocal'].str[11:13]

pm25 = aq[aq['parameter'] == 'pm25'].copy()

hourly = pm25.pivot_table(index='hour', columns='site', values='value')

hourly.round(2)

site  CNSI  Goleta  Santa Barbara
hour
00    5.86    5.10           5.59
01    5.84    9.07           5.47
02    6.08    4.83           5.44
03    5.99    5.30           5.38
04    5.60    3.90           4.62
05    5.63    3.47           4.41
06    5.90    4.10           4.09
07    6.03    5.58           4.00
08    5.96    6.42           6.06
09    6.08    7.42           6.94
10    6.24    7.71           6.03
11    6.67    7.52           7.03
12    7.60    8.19           7.72
13    7.21    8.23           7.53
14    6.56    7.45           7.31
15    6.29    7.00           6.53
16    6.14    6.55           6.69
17    5.78    6.26           6.56
18    5.53    7.03           6.50
19    5.62    7.87           7.66
20    6.00    7.42           7.41
21    5.88    6.77           6.94
22    5.88    6.35           6.34
23    5.83    5.84           5.97