# Day 6: Session 6A - The Join Pattern

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/6a_joining_data.html)

Date: 09/08/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)

goleta['parameter'].value_counts()

parameter
pm25    734
o3      711
pm10    517
Name: count, dtype: int64

In [2]:
goleta.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [46]:
goleta['parameter'].unique

<bound method Series.unique of 0         o3
1         o3
2         o3
3         o3
4         o3
        ...
1957    pm25
1958    pm25
1959    pm25
1960    pm25
1961    pm25
Name: parameter, Length: 1962, dtype: object>

In [3]:
o3 = goleta[goleta['parameter'] == 'o3'].copy()
pm25 = goleta[goleta['parameter'] == 'pm25'].copy()

In [5]:
o3.shape

(711, 15)

In [6]:
pm25.shape

(734, 15)

In [7]:
# time to filter the columns that we want
# we need to provide a list of columns
o3 = o3[['datetimeLocal', 'value']]
o3 = o3.rename(columns = {'value' : 'o3_ppm'})

In [8]:

pm25 = pm25[['datetimeLocal', 'value']]
pm25 = pm25.rename(columns = {'value' : 'pm25_ugm3'})

In [9]:
o3.head()

               datetimeLocal  o3_ppm
0  2024-07-11T18:00:00-07:00   0.025
1  2024-07-11T19:00:00-07:00   0.028
2  2024-07-11T20:00:00-07:00   0.029
3  2024-07-11T21:00:00-07:00   0.027
4  2024-07-11T22:00:00-07:00   0.026

In [10]:
pm25.head()

                  datetimeLocal  pm25_ugm3
1228  2024-07-11T18:00:00-07:00        3.0
1229  2024-07-11T19:00:00-07:00        8.0
1230  2024-07-11T20:00:00-07:00        6.0
1231  2024-07-11T21:00:00-07:00        4.0
1232  2024-07-11T22:00:00-07:00        9.0

to merge :

inner is where both occur `inner`

outer is where either occur `outer`

left is where the left occurs `left`

right is where the right occurs `right`

In [11]:
# there will always be three arguments

paired = pd.merge(o3, pm25, on = 'datetimeLocal')

In [12]:
paired.info

<bound method DataFrame.info of                  datetimeLocal  o3_ppm  pm25_ugm3
0    2024-07-11T18:00:00-07:00   0.025        3.0
1    2024-07-11T19:00:00-07:00   0.028        8.0
2    2024-07-11T20:00:00-07:00   0.029        6.0
3    2024-07-11T21:00:00-07:00   0.027        4.0
4    2024-07-11T22:00:00-07:00   0.026        9.0
..                         ...     ...        ...
699  2024-08-11T13:00:00-07:00   0.032       10.0
700  2024-08-11T14:00:00-07:00   0.032        8.0
701  2024-08-11T15:00:00-07:00   0.038        8.0
702  2024-08-11T16:00:00-07:00   0.039        9.0
703  2024-08-11T17:00:00-07:00   0.036        5.0

[704 rows x 3 columns]>

pd.merge(left, right, on='key')
####        ↑     ↑         ↑
####      the two tables  the column they have in common

In [13]:
paired.shape

(704, 3)

In [18]:
# always specify what type of merge you are going to do

inner = pd.merge(o3, pm25, 
on = 'datetimeLocal', 
how = 'inner')

In [16]:
inner.shape

(704, 3)

In [19]:
left = pd.merge(o3, pm25, 
on = 'datetimeLocal', 
how = 'left')

In [22]:
left.shape

(711, 3)

In [24]:
left.isnull().sum()

datetimeLocal    0
o3_ppm           0
pm25_ugm3        7
dtype: int64

In [26]:
right = pd.merge(o3, pm25, on = 'datetimeLocal', how = 'right')

In [28]:
right.shape

(734, 3)

In [29]:
right.isnull().sum()

datetimeLocal     0
o3_ppm           30
pm25_ugm3         0
dtype: int64

In [30]:
outer = pd.merge(o3, pm25, on = 'datetimeLocal', how = 'outer')

In [33]:
# this is the most conservative way to merge data because it does not remove any rows
print(outer.shape)
outer.isnull().sum()

(741, 3)

datetimeLocal     0
o3_ppm           30
pm25_ugm3         7
dtype: int64

inner = keys in both tables

left = ever ro. of the left table 

right = every row of the right table (wen ever need to use this)

outer = every row of either table

Build a third table, pm10, the same way you built the other two tables: filter goleta to parameter == 'pm10', keep datetimeLocal and value, and rename value to pm10_ugm3. Then merge your PM2.5 table with it two ways, keeping pm25 on the left both times, once using how='inner' and once using how='left', and print both shapes. How many PM2.5 hours have no PM10 reading beside them?

In [47]:
pm10 = goleta[goleta['parameter'] == 'pm10'].copy()
pm10 = pm10[['datetimeLocal', 'value']]
pm10 = pm10.rename(columns = {'value' : 'pm10_ugm3'})

pm10.shape

(517, 2)

In [39]:
inner_1 = pd.merge(pm25, pm10, on = 'datetimeLocal', how = 'inner')

inner_1.shape

(1950, 3)

In [38]:
righty = pd.merge(pm25, pm10, on = 'datetimeLocal', how =  'left')

right.shape

(734, 3)

In [48]:
missing_o3 = right[right['o3_ppm'].isnull()].copy()

missing_o3['datetimeLocal'].str[11:13].value_counts()

datetimeLocal
03    30
Name: count, dtype: int64

In [50]:
# datetimeLocal is a string
o3['datetimeLocal'].str[11:13].value_counts().sort_index()

datetimeLocal
00    31
01    30
02    30
04    31
05    31
06    31
07    31
08    31
09    31
10    31
11    31
12    31
13    31
14    31
15    31
16    31
17    31
18    31
19    31
20    31
21    31
22    31
23    31
Name: count, dtype: int64

In [51]:
paired.sort_values('pm25_ugm3', ascending = False).head(10)

                 datetimeLocal  o3_ppm  pm25_ugm3
464  2024-08-01T01:00:00-07:00   0.011       22.0
142  2024-07-18T01:00:00-07:00   0.022       22.0
619  2024-08-08T01:00:00-07:00   0.025       21.0
673  2024-08-10T10:00:00-07:00   0.029       20.0
609  2024-08-07T15:00:00-07:00   0.043       19.0
585  2024-08-06T13:00:00-07:00   0.040       19.0
349  2024-07-27T01:00:00-07:00   0.008       17.0
293  2024-07-24T15:00:00-07:00   0.027       17.0
295  2024-07-24T17:00:00-07:00   0.026       16.0
586  2024-08-06T14:00:00-07:00   0.041       16.0

In [52]:
paired['o3_ppm'].mean()

0.022438920454545454

In [53]:
paired['pm25_ugm3'].mean()

6.53125

In [54]:
paired.sort_values('pm25_ugm3', ascending = False).head()['o3_ppm'].mean()

0.026000000000000002

In [55]:
# what to do when the key columns have different names

In [56]:
url = 'https://eds-217-essential-python.github.io/data/national_parks.csv'
parks = pd.read_csv(url)

parks = parks[parks['year'] != 'Total'].copy()

parks['region'].value_counts()

region
IM    5682
NE    3637
SE    3442
PW    3194
MW    2578
NC    1547
AK    1018
NT      76
Name: count, dtype: int64

In [ ]:
# this is bascially a dictionary where there are two keys (columns). anything in the list will become values

regions = pd.DataFrame({
    'code': ['AK', 'IM', 'MW', 'NC', 'NE', 'PW', 'SE'],
    'region_name': ['Alaska', 'Intermountain', 'Midwest', 'National Capital',
                    'Northeast', 'Pacific West', 'Southeast'],
})

regions

  code       region_name
0   AK            Alaska
1   IM     Intermountain
2   MW           Midwest
3   NC  National Capital
4   NE         Northeast
5   PW      Pacific West
6   SE         Southeast

In [58]:
parks.head()

,year,gnis_id,geometry,metadata,number_of_records,parkname,region,state,unit_code,unit_name,unit_type,visitors
0,1904,1163670,POLYGON,NaN,1,Crater Lake,PW,OR,CRLA,Crater Lake National Park,National Park,1500.0
1,1941,1531834,MULTIPOLYGON,NaN,1,Lake Roosevelt,PW,WA,LARO,Lake Roosevelt National Recreation Area,National Recreation Area,0.0
2,1961,2055170,MULTIPOLYGON,NaN,1,Lewis and Clark,PW,WA,LEWI,Lewis and Clark National Historical Park,National Historical Park,69000.0
3,1935,1530459,MULTIPOLYGON,NaN,1,Olympic,PW,WA,OLYM,Olympic National Park,National Park,2200.0
4,1982,277263,POLYGON,NaN,1,Santa Monica Mountains,PW,CA,SAMO,Santa Monica Mountains National Recreation Area,National Recreation Area,468144.0

In [62]:
labelled = pd.merge(parks, regions, left_on = "region", right_on = 'code', how = 'inner')

labelled[['unit_name', 'region', 'region_name', 'year', 'visitors']].head()

,unit_name,region,region_name,year,visitors
0,Crater Lake National Park,PW,Pacific West,1904,1500.0
1,Lake Roosevelt National Recreation Area,PW,Pacific West,1941,0.0
2,Lewis and Clark National Historical Park,PW,Pacific West,1961,69000.0
3,Olympic National Park,PW,Pacific West,1935,2200.0
4,Santa Monica Mountains National Recreation Area,PW,Pacific West,1982,468144.0

In [63]:
pd.merge(left, right, left_on = 'column_in_left', right_on = 'column_in_right')

KeyError: 'column_in_right'