# Day 2: Session 2A - Reading Data into pandas

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/2a_reading_data.html)

Date: 09/01/2026

df.head()                  # what does a row look like

df.shape                   # how big

df.info()                  # types, and how much of each column is filled in

df.isnull().sum()          # how many values are missing, column by column

df.describe()              # what do the numbers look like

df['col'].value_counts()   # what is in the text columns

In [1]:
import pandas as pd # import the panda package

In [2]:
url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv' # import the url; can also be file path

In [3]:
goleta = pd.read_csv(url) # display the goleta dataframe and saving as goleta
goleta.head() # show the head of the dataframe; can put any value to see how many rows you want

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

df = pd.read_csv('https://example.org/data.csv')   # from the web


df = pd.read_csv('data/measurements.csv')          # from a folder next to your notebook; the file must exist!

In [4]:
url_sb = 'https://eds-217-essential-python.github.io/data/openaq_santa_barbara_measurments.csv'
santa_barbara = pd.read_csv(url_sb)
santa_barbara.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,27499,Santa Barbara,o3,0.022,ppm,2024-07-11T01:00:00+00:00,2024-07-10T18:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T02:00:00+00:00,2024-07-10T19:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T03:00:00+00:00,2024-07-10T20:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T04:00:00+00:00,2024-07-10T21:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,27499,Santa Barbara,o3,0.016,ppm,2024-07-11T05:00:00+00:00,2024-07-10T22:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [5]:
goleta['value'].head() # to display the head of the column "value" and display the first five rows

0    0.025
1    0.028
2    0.029
3    0.027
4    0.026
Name: value, dtype: float64

In [6]:
type(goleta['value'])
print(type(goleta['value']))

<class 'pandas.core.series.Series'>

In [7]:
list_of_columns = ['value', 'unit']

goleta[list_of_columns]

       value   unit
0      0.025    ppm
1      0.028    ppm
2      0.029    ppm
3      0.027    ppm
4      0.026    ppm
...      ...    ...
1957  10.000  µg/m³
1958   8.000  µg/m³
1959   8.000  µg/m³
1960   9.000  µg/m³
1961   5.000  µg/m³

[1962 rows x 2 columns]

In [8]:
single_col = ['value']
one_column_df = goleta[single_col]
type[one_column_df]

type[       value
0      0.025
1      0.028
2      0.029
3      0.027
4      0.026
...      ...
1957  10.000
1958   8.000
1959   8.000
1960   9.000
1961   5.000

[1962 rows x 1 columns]]

In [9]:
print(type(goleta))
print(type(goleta['value']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [10]:
new_series_para = goleta['parameter'] # pulling this column out of the dataframe to make a series.  
print(type(new_series_para)) # using the print(type()) function to check the type of the column to make sure its series
new_series_para.head()

<class 'pandas.core.series.Series'>

0    o3
1    o3
2    o3
3    o3
4    o3
Name: parameter, dtype: object

In [11]:
column_names = goleta.columns # to look at columns in a dataframe; great for exploratory
column_names.to_list()

['location_id',
 'location_name',
 'parameter',
 'value',
 'unit',
 'datetimeUtc',
 'datetimeLocal',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']

In [12]:
print(column_names[0]) # to see the first column of the dataframe

column_names[-1] # to see the last column in the dataframe

location_id

'provider'

In [13]:
len(column_names) # to see how long anything is; use len()

15

In [14]:
len(goleta) # to see the number of rows of a dataframe

1962

In [15]:
keep = ['location_name', 'parameter', 'value', 'unit'] # this is a great way to filter out a dataframe with only the columns you want
goleta[keep]

     location_name parameter   value   unit
0           Goleta        o3   0.025    ppm
1           Goleta        o3   0.028    ppm
2           Goleta        o3   0.029    ppm
3           Goleta        o3   0.027    ppm
4           Goleta        o3   0.026    ppm
...            ...       ...     ...    ...
1957        Goleta      pm25  10.000  µg/m³
1958        Goleta      pm25   8.000  µg/m³
1959        Goleta      pm25   8.000  µg/m³
1960        Goleta      pm25   9.000  µg/m³
1961        Goleta      pm25   5.000  µg/m³

[1962 rows x 4 columns]

In [16]:
goleta_by_time = pd.read_csv(url, index_col = 'datetimeLocal') # here we are choosing the index

In [17]:
goleta_by_time.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit',
       'datetimeUtc', 'timezone', 'latitude', 'longitude', 'country_iso',
       'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='object')

In [18]:

goleta_utc = pd.read_csv(url, index_col = 'datetimeUtc')
goleta_utc.head()

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
datetimeUtc,,,,,,,,,,,,,,
2024-07-12T01:00:00+00:00,1186,Goleta,o3,0.025,ppm,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T02:00:00+00:00,1186,Goleta,o3,0.028,ppm,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T03:00:00+00:00,1186,Goleta,o3,0.029,ppm,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T04:00:00+00:00,1186,Goleta,o3,0.027,ppm,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T05:00:00+00:00,1186,Goleta,o3,0.026,ppm,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [19]:
goleta_utc.index.nunique()

742

# Day 2: Session 2B - Exploring a DataFrame

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/2b_exploring_data.html)

Date: 09/01/2026

In [20]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)

In [21]:
goleta.head() # look at the first five rows

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [22]:
goleta.tail() # look at the last five rows

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1957,1186,Goleta,pm25,10.0,µg/m³,2024-08-11T20:00:00+00:00,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1958,1186,Goleta,pm25,8.0,µg/m³,2024-08-11T21:00:00+00:00,2024-08-11T14:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1959,1186,Goleta,pm25,8.0,µg/m³,2024-08-11T22:00:00+00:00,2024-08-11T15:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1960,1186,Goleta,pm25,9.0,µg/m³,2024-08-11T23:00:00+00:00,2024-08-11T16:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1961,1186,Goleta,pm25,5.0,µg/m³,2024-08-12T00:00:00+00:00,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [23]:
goleta.shape # shows the rows and the columns (a tupple) -> (rows, cols)

(1962, 15)

In [24]:
print("rows: ", goleta.shape[0])
print("columns: ", goleta.shape[1])

print(f"(rows, columns) = {goleta.shape}")

rows:  1962
columns:  15
(rows, columns) = (1962, 15)

In [25]:
goleta.columns.tolist() # shows the dataframes columns and puts it into a list. does not do too much

['location_id',
 'location_name',
 'parameter',
 'value',
 'unit',
 'datetimeUtc',
 'datetimeLocal',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']

In [26]:
print(goleta.dtypes) # to see what type of data the columns are within the dataframe; always do

location_id        int64
location_name     object
parameter         object
value            float64
unit              object
datetimeUtc       object
datetimeLocal     object
timezone          object
latitude         float64
longitude        float64
country_iso      float64
isMobile         float64
isMonitor        float64
owner_name        object
provider          object
dtype: object

In [27]:
goleta.info() # very important because it combines the shape, the column names, the types, and, critically, how many non-null 
# values each column has

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1962 entries, 0 to 1961
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    1962 non-null   int64
 1   location_name  1962 non-null   object
 2   parameter      1962 non-null   object
 3   value          1962 non-null   float64
 4   unit           1962 non-null   object
 5   datetimeUtc    1962 non-null   object
 6   datetimeLocal  1962 non-null   object
 7   timezone       1962 non-null   object
 8   latitude       1962 non-null   float64
 9   longitude      1962 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     1962 non-null   object
 14  provider       1962 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 230.1+ KB

In [28]:
goleta['country_iso'] # viewing the column and its contents

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1957   NaN
1958   NaN
1959   NaN
1960   NaN
1961   NaN
Name: country_iso, Length: 1962, dtype: float64

In [29]:
goleta.isnull().sum() # shows the sum of the null values for each column.

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      1962
isMobile         1962
isMonitor        1962
owner_name          0
provider            0
dtype: int64

In [30]:
url_sb1 = 'https://eds-217-essential-python.github.io/data/openaq_santa_barbara_measurments.csv'
santa_barbara_1 = pd.read_csv(url_sb1)

santa_barbara_1.info() 

# this is to load in the dataset for SB and see the dataframe breakdown. that way we can cross-reference the
# other DF for Goleta. Important to see if both of the dataframes have the same empty columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2266 entries, 0 to 2265
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    2266 non-null   int64
 1   location_name  2266 non-null   object
 2   parameter      2266 non-null   object
 3   value          2266 non-null   float64
 4   unit           2266 non-null   object
 5   datetimeUtc    2266 non-null   object
 6   datetimeLocal  2266 non-null   object
 7   timezone       2266 non-null   object
 8   latitude       2266 non-null   float64
 9   longitude      2266 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     2266 non-null   object
 14  provider       2266 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 265.7+ KB

In [31]:
goleta.describe() # gives you count, mean, standard deviation, min, max, and quartiles for every numeric column

,location_id,value,latitude,longitude,country_iso,isMobile,isMonitor
count,1962.0,1962.000000,1.962000e+03,1.962000e+03,0.0,0.0,0.0
mean,1186.0,6.378173,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
std,0.0,7.313763,2.132172e-14,2.842896e-14,NaN,NaN,NaN
min,1186.0,-4.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
25%,1186.0,0.027000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
50%,1186.0,5.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
75%,1186.0,10.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
max,1186.0,40.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN

In [32]:
santa_barbara_1.describe() # gives you count, mean, standard deviation, min, max, and quartiles for every numeric column

,location_id,value,latitude,longitude,country_iso,isMobile,isMonitor
count,2266.0,2266.000000,2266.00000,2266.00000,0.0,0.0,0.0
mean,27499.0,8.030251,34.42775,-119.69091,NaN,NaN,NaN
std,0.0,8.761784,0.00000,0.00000,NaN,NaN,NaN
min,27499.0,-1.000000,34.42775,-119.69091,NaN,NaN,NaN
25%,27499.0,0.024000,34.42775,-119.69091,NaN,NaN,NaN
50%,27499.0,6.000000,34.42775,-119.69091,NaN,NaN,NaN
75%,27499.0,13.000000,34.42775,-119.69091,NaN,NaN,NaN
max,27499.0,47.000000,34.42775,-119.69091,NaN,NaN,NaN

In [33]:
goleta['unit'].value_counts() # shows us for each unique value of the dataframe, how many are in it.

unit
µg/m³    1251
ppm       711
Name: count, dtype: int64

In [34]:
print(goleta['parameter'].value_counts()) 
# showing us the parameter column and how many types of data populate the column

parameter
pm25    734
o3      711
pm10    517
Name: count, dtype: int64

In [35]:
list_of_counts = goleta['datetimeLocal'].value_counts().to_list() 
# whitespace does not matter if you are in the brackets []

In [ ]:
new_names = { # renaming column names to make them more readible
    'datetimeUtc' : 'datetime_UTC',
    'datetimeLocal' : 'datetime_local'
}

In [41]:
type(new_names)

dict

In [43]:
new_names['datetimeUtc']

'datetime_UTC'

In [45]:
?goleta.rename # to look at function purposes.

Object `goleta.rename # to look at function purposes.` not found.

In [48]:
goleta_new = goleta.rename(columns = new_names)

In [ ]:
newer_names = {
    'value' : 'concentration',
    'parameter' : 'pollutant'
}
goleta_newer = goleta.rename(columns = newer_names)

In [55]:
goleta.columns.tolist()

['location_id',
 'location_name',
 'parameter',
 'value',
 'unit',
 'datetimeUtc',
 'datetimeLocal',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']

In [54]:
goleta_newer.columns.tolist()

['location_id',
 'location_name',
 'pollutant',
 'concentration',
 'unit',
 'datetimeUtc',
 'datetimeLocal',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']