# Day 4: Session 4A - Missing, Duplicated, Miscast

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/4a_cleaning_data.html)

Date: 09/03/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/marine_microplastics.csv'
plastics = pd.read_csv(url)

In [2]:
plastics.shape

(16245, 22)

In [3]:
plastics.head()

,OBJECTID,Oceans,Regions,SubRegions,Sampling Method,Measurement,Unit,Density Range,Density Class,Short Reference,...,Organization,Keywords,Accession Number,Accession Link,Latitude,Longitude,Date,GlobalID,x,y
0,10008,Atlantic Ocean,NaN,NaN,Grab sample,0.020000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,-58.428300,-64.1640,2/3/2017 12:00:00 AM,1e5b8e71-037b-4887-a276-f1e4552acb1f,-64.1640,-58.428300
1,8680,Atlantic Ocean,NaN,NaN,Grab sample,0.008000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,-51.308200,-60.5467,11/17/2013 12:00:00 AM,a40f7f7c-1025-4aac-ad16-ee4cba196870,-60.5467,-51.308200
2,13257,Pacific Ocean,NaN,NaN,Manta net,0.019886,pieces/m3,0.005-1,Medium,Faure et al.2015,...,"Oceaneye Association, Switzerland",Oceaneye Association; Citizen Science,276422,https://www.ncei.noaa.gov/access/metadata/land...,-51.826667,-72.5750,12/26/2015 12:00:00 AM,febf79b8-7e2c-46e6-bc15-e08492ec2029,-72.5750,-51.826667
3,9676,Atlantic Ocean,NaN,NaN,Grab sample,0.018000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,-31.696000,-48.5600,8/11/2015 12:00:00 AM,a77121b2-e113-444e-82d9-7af11d62fdd2,-48.5600,-31.696000
4,6427,Pacific Ocean,NaN,NaN,Neuston net,0.000000,pieces/m3,0-0.0005,Very Low,Law et al.2014,...,Sea Education Association,SEA,211008,https://www.ncei.noaa.gov/access/metadata/land...,6.350000,-121.8500,12/18/2002 12:00:00 AM,be27c450-02ca-4261-8d89-cae21108e6cc,-121.8500,6.350000

In [4]:
plastics.describe()

,OBJECTID,Measurement,Accession Number,Latitude,Longitude,x,y
count,16245.000000,10453.000000,16245.000000,16245.000000,16245.000000,16245.000000,16245.000000
mean,11167.305263,225.807370,239277.512096,27.726941,-73.294063,-73.294063,27.726941
std,7138.627239,2597.118472,27283.260088,15.479316,28.652511,28.652511,15.479316
min,1.000000,0.000000,170967.000000,-69.992100,-131.289250,-131.289250,-69.992100
25%,4062.000000,0.000000,211007.000000,22.200000,-94.823300,-94.823300,22.200000
50%,11871.000000,0.008000,259486.000000,28.780300,-77.390000,-77.390000,28.780300
75%,17758.000000,0.060476,259486.000000,33.950063,-63.680000,-63.680000,33.950063
max,22338.000000,110480.000000,285700.000000,88.961300,5.596789,5.596789,88.961300

In [5]:
plastics['Oceans'].unique()

array(['Atlantic Ocean', 'Pacific Ocean', nan, 'Southern Ocean', 'Arctic Ocean'], dtype=object)

In [6]:
plastics.columns.tolist()

['OBJECTID',
 'Oceans',
 'Regions',
 'SubRegions',
 'Sampling Method',
 'Measurement',
 'Unit',
 'Density Range',
 'Density Class',
 'Short Reference',
 'Long Reference',
 'DOI',
 'Organization',
 'Keywords',
 'Accession Number',
 'Accession Link',
 'Latitude',
 'Longitude',
 'Date',
 'GlobalID',
 'x',
 'y']

In [7]:
plastics.isnull().sum()

OBJECTID                0
Oceans                271
Regions              8249
SubRegions          15657
Sampling Method         0
Measurement          5792
Unit                    0
Density Range           0
Density Class           0
Short Reference         0
Long Reference          0
DOI                     0
Organization            0
Keywords               18
Accession Number        0
Accession Link          0
Latitude                0
Longitude               0
Date                    0
GlobalID                0
x                       0
y                       0
dtype: int64

In [8]:
plastics.isnull().sum().sort_values(ascending = False).head(5)

SubRegions     15657
Regions         8249
Measurement     5792
Oceans           271
Keywords          18
dtype: int64

In [9]:
plastics.dropna()
# with no arguments this drops 96% of the dataset. This is not good data science

,OBJECTID,Oceans,Regions,SubRegions,Sampling Method,Measurement,Unit,Density Range,Density Class,Short Reference,...,Organization,Keywords,Accession Number,Accession Link,Latitude,Longitude,Date,GlobalID,x,y
47,22079,Atlantic Ocean,Gulf of Mexico,Tampa Bay,Van Dorn sampler,0.000000,pieces/m3,0-0.0005,Very Low,McEachern et al. 2019,...,University of South Florida,Tampa Bay,285700,https://www.ncei.noaa.gov/access/metadata/land...,27.923700,-82.480700,8/9/2016 12:00:00 AM,d1ee225b-9f64-403f-a385-1ca1c3d85218,-82.480700,27.923700
81,11242,Atlantic Ocean,Mediterranean Sea,Western Basin,Manta net,2.381713,pieces/m3,1-10,High,Pedrotti et al.2022,...,Sorbonne Universités,R/V Tara,270530,https://www.ncei.noaa.gov/access/metadata/land...,38.272900,-0.276660,10/29/2014 12:00:00 AM,e55d6850-41b1-4157-9d90-6b079c2de2ed,-0.276660,38.272900
82,13234,Atlantic Ocean,Mediterranean Sea,Alboran Sea,Manta net,0.090741,pieces/m3,0.005-1,Medium,Faure et al.2015,...,"Oceaneye Association, Switzerland",Oceaneye Association; Citizen Science,276422,https://www.ncei.noaa.gov/access/metadata/land...,36.420000,-4.343333,8/19/2014 12:00:00 AM,80ca5fe0-1ef1-4e33-9bd2-dc71f2709af4,-4.343333,36.420000
116,22056,Atlantic Ocean,Gulf of Mexico,Tampa Bay,Van Dorn sampler,0.000000,pieces/m3,0-0.0005,Very Low,McEachern et al. 2019,...,University of South Florida,Tampa Bay,285700,https://www.ncei.noaa.gov/access/metadata/land...,27.989900,-82.631600,6/8/2016 12:00:00 AM,2129720d-9d70-4397-8510-ce74933e229c,-82.631600,27.989900
137,10718,Atlantic Ocean,Mediterranean Sea,Balearic Sea,Manta net,0.335000,pieces/m3,0.005-1,Medium,de Haan et al.2019,...,University of Barcelona,RV Angeles Alvari¤o/RV IV Lluerna,253140,https://www.ncei.noaa.gov/access/metadata/land...,41.753333,3.063333,6/5/2015 12:00:00 AM,549a1ca6-6219-4054-b1f5-492fedda5778,3.063333,41.753333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16087,22233,Atlantic Ocean,Gulf of Mexico,Tampa Bay,Plankton net,4.900000,pieces/m3,1-10,High,McEachern et al. 2019,...,University of South Florida,Tampa Bay,285700,https://www.ncei.noaa.gov/access/metadata/land...,27.852400,-82.409300,10/11/2016 12:00:00 AM,ea99b170-5826-4cbd-a5c1-289dd27f2aa5,-82.409300,27.852400
16150,22170,Atlantic Ocean,Gulf of Mexico,Tampa Bay,Van Dorn sampler,0.000000,pieces/m3,0-0.0005,Very Low,McEachern et al. 2019,...,University of South Florida,Tampa Bay,285700,https://www.ncei.noaa.gov/access/metadata/land...,27.708400,-82.609200,5/16/2017 12:00:00 AM,99ab2669-4b06-48d0-9511-dcee0e3c52fc,-82.609200,27.708400
16190,9982,Atlantic Ocean,Gulf of Mexico,Coastal Waters of Florida,Grab sample,0.001000,pieces/m3,0.0005-0.005,Low,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,25.775500,-81.374700,12/28/2016 12:00:00 AM,8ed5637f-82ea-43a8-8f23-6c6add6d89d7,-81.374700,25.775500
16212,10829,Atlantic Ocean,Mediterranean Sea,Balearic Sea,Manta net,0.342000,pieces/m3,0.005-1,Medium,de Haan et al.2022,...,University of Barcelona,Citizen science; Surf board; Kayak,253923,https://www.ncei.noaa.gov/access/metadata/land...,41.849824,3.147244,2/6/2021 12:00:00 AM,4b2bb8a2-6363-4be5-8322-944885f77844,3.147244,41.849824
16240,10726,Atlantic Ocean,Mediterranean Sea,Balearic Sea,Manta net,0.326000,pieces/m3,0.005-1,Medium,de Haan et al.2022,...,University of Barcelona,Citizen science; Surf board; Kayak,253923,https://www.ncei.noaa.gov/access/metadata/land...,40.910469,0.833376,3/11/2021 12:00:00 AM,b840a79b-6d98-4def-ac53-5447be1531b9,0.833376,40.910469

In [10]:
measured = plastics.dropna(subset = ['Measurement'])
# this is not a completely new dataframe. You need to add `.copy()` in the end

measured = plastics.dropna(subset = ['Measurement']).copy()
# this makes a new dataframe and is saved in our environment

In [11]:
measured.shape

(10453, 22)

In [12]:
plastics['Unit'].value_counts()

Unit
pieces/m3           10178
pieces/10 mins       5792
pieces kg-1 d.w.      275
Name: count, dtype: int64

In [13]:
measured['Unit'].value_counts()

Unit
pieces/m3           10178
pieces kg-1 d.w.      275
Name: count, dtype: int64

In [14]:
# we can use fillna to replace missing data

In [15]:
plastics['Regions'] = plastics['Regions'].fillna('Unspecified')

In [16]:
plastics['Regions'].value_counts().head()

Regions
Unspecified          8249
Gulf of Mexico       4817
Caribbean Sea        1886
Mediterranean Sea     345
North Sea             252
Name: count, dtype: int64

In [17]:
plastics['Regions']

0              Unspecified
1              Unspecified
2              Unspecified
3              Unspecified
4              Unspecified
               ...
16240    Mediterranean Sea
16241          Unspecified
16242        Caribbean Sea
16243          Unspecified
16244          Unspecified
Name: Regions, Length: 16245, dtype: object

In [18]:
print(measured['Unit'].value_counts())

new_regions_columns = plastics['Regions'].fillna('Unspecified')

plastics['Regions'] = new_regions_columns

Unit
pieces/m3           10178
pieces kg-1 d.w.      275
Name: count, dtype: int64

In [19]:
plastics.isnull().sum().sort_values(ascending = False).head(5)

SubRegions     15657
Measurement     5792
Oceans           271
Keywords          18
Regions            0
dtype: int64

In [20]:
sub_reg = plastics["SubRegions"].fillna('Unspecified')

plastics['SubRegions'] = sub_reg

plastics

,OBJECTID,Oceans,Regions,SubRegions,Sampling Method,Measurement,Unit,Density Range,Density Class,Short Reference,...,Organization,Keywords,Accession Number,Accession Link,Latitude,Longitude,Date,GlobalID,x,y
0,10008,Atlantic Ocean,Unspecified,Unspecified,Grab sample,0.020000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,-58.428300,-64.164000,2/3/2017 12:00:00 AM,1e5b8e71-037b-4887-a276-f1e4552acb1f,-64.164000,-58.428300
1,8680,Atlantic Ocean,Unspecified,Unspecified,Grab sample,0.008000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,-51.308200,-60.546700,11/17/2013 12:00:00 AM,a40f7f7c-1025-4aac-ad16-ee4cba196870,-60.546700,-51.308200
2,13257,Pacific Ocean,Unspecified,Unspecified,Manta net,0.019886,pieces/m3,0.005-1,Medium,Faure et al.2015,...,"Oceaneye Association, Switzerland",Oceaneye Association; Citizen Science,276422,https://www.ncei.noaa.gov/access/metadata/land...,-51.826667,-72.575000,12/26/2015 12:00:00 AM,febf79b8-7e2c-46e6-bc15-e08492ec2029,-72.575000,-51.826667
3,9676,Atlantic Ocean,Unspecified,Unspecified,Grab sample,0.018000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,-31.696000,-48.560000,8/11/2015 12:00:00 AM,a77121b2-e113-444e-82d9-7af11d62fdd2,-48.560000,-31.696000
4,6427,Pacific Ocean,Unspecified,Unspecified,Neuston net,0.000000,pieces/m3,0-0.0005,Very Low,Law et al.2014,...,Sea Education Association,SEA,211008,https://www.ncei.noaa.gov/access/metadata/land...,6.350000,-121.850000,12/18/2002 12:00:00 AM,be27c450-02ca-4261-8d89-cae21108e6cc,-121.850000,6.350000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16240,10726,Atlantic Ocean,Mediterranean Sea,Balearic Sea,Manta net,0.326000,pieces/m3,0.005-1,Medium,de Haan et al.2022,...,University of Barcelona,Citizen science; Surf board; Kayak,253923,https://www.ncei.noaa.gov/access/metadata/land...,40.910469,0.833376,3/11/2021 12:00:00 AM,b840a79b-6d98-4def-ac53-5447be1531b9,0.833376,40.910469
16241,9366,Atlantic Ocean,Unspecified,Unspecified,Grab sample,0.011000,pieces/m3,0.005-1,Medium,Barrows et al.2018,...,Adventure Scientist,Adventure Scientist/Citizen Science,211009,https://www.ncei.noaa.gov/access/metadata/land...,17.100000,-47.550000,2/1/2015 12:00:00 AM,fd4db6d6-aed7-48b1-a22b-402557112e2f,-47.550000,17.100000
16242,4683,Atlantic Ocean,Caribbean Sea,Unspecified,Neuston net,0.021600,pieces/m3,0.005-1,Medium,Law et al.2010,...,Sea Education Association,SEA,211007,https://www.ncei.noaa.gov/access/metadata/land...,21.390000,-81.960000,3/14/2001 12:00:00 AM,83a8208e-2d06-4ad9-bcd9-81e29d57e0aa,-81.960000,21.390000
16243,6043,Atlantic Ocean,Unspecified,Unspecified,Neuston net,0.000000,pieces/m3,0-0.0005,Very Low,Law et al.2010,...,Sea Education Association,SEA,211007,https://www.ncei.noaa.gov/access/metadata/land...,24.140000,-81.980000,5/1/2008 12:00:00 AM,0fd72d83-cd27-42e1-b63a-b015c23b28d2,-81.980000,24.140000
16244,20169,Atlantic Ocean,Unspecified,Unspecified,Hand picking,NaN,pieces/10 mins,40-200,High,Tunnell et al. 2020,...,University of Texas Marine Science Institute,Nurdle Patrol,259486,https://www.ncei.noaa.gov/access/metadata/land...,39.924800,-75.127200,10/28/2021 12:00:00 AM,fc84069e-c782-4c3d-bf6b-265535969d8e,-75.127200,39.924800

In [21]:
plastics.duplicated().sum()

0

In [22]:
plastics.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['OBJECTID', 'Oceans', 'Regions', 'SubRegions', 'Sampling Method',
       'Measurement', 'Unit', 'Density Range', 'Density Class',
       'Short Reference', 'Long Reference', 'DOI', 'Organization', 'Keywords',
       'Accession Number', 'Accession Link', 'Latitude', 'Longitude', 'Date',
       'GlobalID', 'x', 'y'],
      dtype='object')>

In [23]:
plastics[['OBJECTID', 'GlobalID', 'Latitude', 'Longitude', 'Date', 'Measurement']].head(3)

,OBJECTID,GlobalID,Latitude,Longitude,Date,Measurement
0,10008,1e5b8e71-037b-4887-a276-f1e4552acb1f,-58.428300,-64.1640,2/3/2017 12:00:00 AM,0.020000
1,8680,a40f7f7c-1025-4aac-ad16-ee4cba196870,-51.308200,-60.5467,11/17/2013 12:00:00 AM,0.008000
2,13257,febf79b8-7e2c-46e6-bc15-e08492ec2029,-51.826667,-72.5750,12/26/2015 12:00:00 AM,0.019886

In [24]:
sample_column = ['Latitude', 'Longitude', 'Date', 'Measurement', 'Unit']

plastics.duplicated(subset=sample_column).sum()

856

In [25]:
deduplicated = plastics.drop_duplicates(subset = sample_column)
deduplicated.shape

(15389, 22)

In [26]:
repeats = plastics[plastics.duplicated(subset = sample_column, keep = False)]
print(repeats.shape)

repeats[['Measurement', 'Unit', 'Sampling Method', 'Short Reference']].head(6)

(1465, 22)

,Measurement,Unit,Sampling Method,Short Reference
6,0.000000,pieces kg-1 d.w.,Megacorer,Courtene-Jones et al. 2020
37,2115.655853,pieces/m3,PVC cylinder,Alvarez-Zeferino et al. 2020
40,NaN,pieces/10 mins,Hand picking,Tunnell et al. 2020
46,NaN,pieces/10 mins,Hand picking,Tunnell et al. 2020
52,0.000000,pieces/m3,Neuston net,Law et al.2010
73,0.002088,pieces/m3,Neuston net,Law et al.2010

In [27]:
# this is being applied to the whole dataset. typically when a line of code appplies
# to the whole DF then it is being used as a filter.
plastics.duplicated(subset = sample_column, keep = False)

0        False
1        False
2        False
3        False
4        False
         ...
16240    False
16241    False
16242    False
16243    False
16244    False
Length: 16245, dtype: bool

In [28]:
(repeats['Measurement'] == 0).sum()

652

In [29]:
plastics.dtypes

OBJECTID              int64
Oceans               object
Regions              object
SubRegions           object
Sampling Method      object
Measurement         float64
Unit                 object
Density Range        object
Density Class        object
Short Reference      object
Long Reference       object
DOI                  object
Organization         object
Keywords             object
Accession Number      int64
Accession Link       object
Latitude            float64
Longitude           float64
Date                 object
GlobalID             object
x                   float64
y                   float64
dtype: object

float64 is a decimal number

int64 a whole number

object is the catch-all for text

In [32]:
plastics['Oceans'].value_counts()

Oceans
Atlantic Ocean    14483
Pacific Ocean      1402
Arctic Ocean         69
Southern Ocean       20
Name: count, dtype: int64

In [ ]:
# use astype() to change the type of a data series
plastics['Oceans'].astype(str)

0        Atlantic Ocean
1        Atlantic Ocean
2         Pacific Ocean
3        Atlantic Ocean
4         Pacific Ocean
              ...
16240    Atlantic Ocean
16241    Atlantic Ocean
16242    Atlantic Ocean
16243    Atlantic Ocean
16244    Atlantic Ocean
Name: Oceans, Length: 16245, dtype: object

In [ ]:
plastics["Longitude"].astype(int)
# not good because we want to keep the decimal places when it comes to coordinates

0        -64
1        -60
2        -72
3        -48
4       -121
        ...
16240      0
16241    -47
16242    -81
16243    -81
16244    -75
Name: Longitude, Length: 16245, dtype: int64

In [41]:
# this is making a new column and putting it back into the df but now a as a string.
plastics['Accession Number'] = plastics['Accession Number'].astype(str)

In [43]:
plastics['Accession Number']

0        211009
1        211009
2        276422
3        211009
4        211008
          ...
16240    253923
16241    211009
16242    211007
16243    211007
16244    259486
Name: Accession Number, Length: 16245, dtype: object

In [ ]:
# this will not work because there is no number associated with the atlantic ocean or red sea. 
# plastics['Oceans'].astype(float)

ValueError: could not convert string to float: 'Atlantic Ocean'

step for DS

1. define the columns 

2. create a filter using the columns

3. filter the DF using the filter

4. figure out a way to fill in the NA columns