# Day 6: Session 6B - Long and Wide

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/6b_reshaping_data.html)

Date: 09/08/2026

In [1]:
import pandas as pd

base = 'https://eds-217-essential-python.github.io/data/'

goleta = pd.read_csv(base + 'openaq_goleta_measurments.csv')
santa_barbara = pd.read_csv(base + 'openaq_santa_barbara_measurments.csv')
cnsi = pd.read_csv(base + 'openaq_CNSI_measurments.csv')

print(goleta.shape)
print(santa_barbara.shape)
print(cnsi.shape)

(1962, 15)
(2266, 15)
(714, 15)

In [2]:
goleta.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [3]:
santa_barbara.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,27499,Santa Barbara,o3,0.022,ppm,2024-07-11T01:00:00+00:00,2024-07-10T18:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T02:00:00+00:00,2024-07-10T19:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T03:00:00+00:00,2024-07-10T20:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T04:00:00+00:00,2024-07-10T21:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,27499,Santa Barbara,o3,0.016,ppm,2024-07-11T05:00:00+00:00,2024-07-10T22:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [4]:
cnsi.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,2812592,CNSI Roof Top,pm25,4.4,µg/m³,2024-07-11T01:00:00+00:00,2024-07-10T18:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity
1,2812592,CNSI Roof Top,pm25,4.4,µg/m³,2024-07-11T02:00:00+00:00,2024-07-10T19:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity
2,2812592,CNSI Roof Top,pm25,4.6,µg/m³,2024-07-11T04:00:00+00:00,2024-07-10T21:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity
3,2812592,CNSI Roof Top,pm25,4.2,µg/m³,2024-07-11T05:00:00+00:00,2024-07-10T22:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity
4,2812592,CNSI Roof Top,pm25,4.5,µg/m³,2024-07-11T06:00:00+00:00,2024-07-10T23:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity

In [5]:
aq = pd.concat([goleta, santa_barbara, cnsi])

aq.shape

(4942, 15)